// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHh0MKR8xU1s6kCJFI_J3alLA8pJXJokc',
    appId: '1:305119911187:web:5f161fcc1758e9c1e88ee6',
    messagingSenderId: '305119911187',
    projectId: 'door-lock-a6658',
    authDomain: 'door-lock-a6658.firebaseapp.com',
    databaseURL: 'https://door-lock-a6658-default-rtdb.firebaseio.com',
    storageBucket: 'door-lock-a6658.appspot.com',
    measurementId: 'G-HJYJ9YVXMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT4ZcS0N1QmeJvIwgr7E0hDGJWAArfcJw',
    appId: '1:305119911187:android:97ab5c79746b1d03e88ee6',
    messagingSenderId: '305119911187',
    projectId: 'door-lock-a6658',
    databaseURL: 'https://door-lock-a6658-default-rtdb.firebaseio.com',
    storageBucket: 'door-lock-a6658.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhxt4zJ6lYu0yK9lcCnCNNb2MiUNnT2ls',
    appId: '1:305119911187:ios:12dee75d89fdae2ae88ee6',
    messagingSenderId: '305119911187',
    projectId: 'door-lock-a6658',
    databaseURL: 'https://door-lock-a6658-default-rtdb.firebaseio.com',
    storageBucket: 'door-lock-a6658.appspot.com',
    iosClientId: '305119911187-rr6thnh5pjrdpb4coom5gr8h1jh8o1tp.apps.googleusercontent.com',
    iosBundleId: 'com.example.doorLock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhxt4zJ6lYu0yK9lcCnCNNb2MiUNnT2ls',
    appId: '1:305119911187:ios:12dee75d89fdae2ae88ee6',
    messagingSenderId: '305119911187',
    projectId: 'door-lock-a6658',
    databaseURL: 'https://door-lock-a6658-default-rtdb.firebaseio.com',
    storageBucket: 'door-lock-a6658.appspot.com',
    iosClientId: '305119911187-rr6thnh5pjrdpb4coom5gr8h1jh8o1tp.apps.googleusercontent.com',
    iosBundleId: 'com.example.doorLock',
  );
}
